# Configuration for CI build at https://travis-ci.org/hsz/idea-nodesecurity

language: java

jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=183.2940.10
  - IDEA_VERSION=2018.2.4
  - IDEA_VERSION=2018.1.6
  - IDEA_VERSION=2017.3.5
  - IDEA_VERSION=2017.2.7
  - IDEA_VERSION=2017.1.6

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - ./gradlew jacocoTestReport coveralls
